//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolstagis.Web.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dolstagis.Web.Errors.StatusMessages", typeof(StatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you requested is now available &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;. Please update your records (bookmarks/favourites, database records etc)..
        /// </summary>
        internal static string Message301MovedPermanently {
            get {
                return ResourceManager.GetString("Message301MovedPermanently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you requested is currently available &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;. This may change in future, so please continue to use this address to access it..
        /// </summary>
        internal static string Message302Found {
            get {
                return ResourceManager.GetString("Message302Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response to this request is available &lt;a href=&quot;{0}&quot;&gt;here&gt;&lt;/a&gt;..
        /// </summary>
        internal static string Message303SeeOther {
            get {
                return ResourceManager.GetString("Message303SeeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you requested must be accessed through a proxy server &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string Message305UseProxy {
            get {
                return ResourceManager.GetString("Message305UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL you requested has been moved temporarily and is currently available &lt;a href=&quot;{0}&quot;&gt;here&lt;/a&gt;. Please continue to use this URL for future requests..
        /// </summary>
        internal static string Message307TemporaryRedirect {
            get {
                return ResourceManager.GetString("Message307TemporaryRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser sent a request that the server could not understand..
        /// </summary>
        internal static string Message400BadRequest {
            get {
                return ResourceManager.GetString("Message400BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not verify that you are authorised to access the requested URL. Either you specified the wrong credentials (e.g. user name and password) or your browser is not able to supply the correct credentials..
        /// </summary>
        internal static string Message401Unauthorized {
            get {
                return ResourceManager.GetString("Message401Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access the requested URL..
        /// </summary>
        internal static string Message403Forbidden {
            get {
                return ResourceManager.GetString("Message403Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL that you requested was not found..
        /// </summary>
        internal static string Message404NotFound {
            get {
                return ResourceManager.GetString("Message404NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested method is not allowed for this URL..
        /// </summary>
        internal static string Message405MethodNotAllowed {
            get {
                return ResourceManager.GetString("Message405MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appropriate representation of the requested URL could not be found on this server..
        /// </summary>
        internal static string Message406NotAcceptable {
            get {
                return ResourceManager.GetString("Message406NotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy server could not verify that you are authorised to access the requested URL. Either you specified the wrong credentials (e.g. user name and password) or your browser is not able to supply the correct credentials..
        /// </summary>
        internal static string Message407ProxyAuthenticationRequired {
            get {
                return ResourceManager.GetString("Message407ProxyAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timed out waiting for the HTTP request for the client..
        /// </summary>
        internal static string Message408RequestTimeout {
            get {
                return ResourceManager.GetString("Message408RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is no longer available on this server and there is no forwarding address. Please remove all references to this resource..
        /// </summary>
        internal static string Message410Gone {
            get {
                return ResourceManager.GetString("Message410Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request of this method requires a valid Content-Length..
        /// </summary>
        internal static string Message411LengthRequired {
            get {
                return ResourceManager.GetString("Message411LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The precondition on the request for this URL failed..
        /// </summary>
        internal static string Message412PreconditionFailed {
            get {
                return ResourceManager.GetString("Message412PreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of data provided in this request exceeds the capacity limit..
        /// </summary>
        internal static string Message413RequestEntityTooLarge {
            get {
                return ResourceManager.GetString("Message413RequestEntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested URL is too long for this server..
        /// </summary>
        internal static string Message414RequestUriTooLong {
            get {
                return ResourceManager.GetString("Message414RequestUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied request data is not in a format acceptable for the processing of this resource..
        /// </summary>
        internal static string Message415UnsupportedMediaType {
            get {
                return ResourceManager.GetString("Message415UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the range-specifier values in the Range request-header field overlap the current extent of the selected resource..
        /// </summary>
        internal static string Message416RequestedRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("Message416RequestedRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expectation given in the Expect: request header field could not be met by this server..
        /// </summary>
        internal static string Message417ExpectationFailed {
            get {
                return ResourceManager.GetString("Message417ExpectationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a teapot.
        /// </summary>
        internal static string Message418ImATeapot {
            get {
                return ResourceManager.GetString("Message418ImATeapot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your calm.
        /// </summary>
        internal static string Message420EnhanceYourCalm {
            get {
                return ResourceManager.GetString("Message420EnhanceYourCalm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server understands the media type of the request entity, but was unable to process the contained instructions..
        /// </summary>
        internal static string Message422UnprocessableEntity {
            get {
                return ResourceManager.GetString("Message422UnprocessableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource is currently locked. The lock must be released, or proper identification given before the method can be applied..
        /// </summary>
        internal static string Message423Locked {
            get {
                return ResourceManager.GetString("Message423Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method could not be performed on the resource because the requested action depended on another action and that other action failed..
        /// </summary>
        internal static string Message424FailedDependency {
            get {
                return ResourceManager.GetString("Message424FailedDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource can only be retrieved using SSL. The server is willing to upgrade the current connection to SSL, but your client doesn&apos;t support it. Either upgrade your client, or try requesting the page using https://.
        /// </summary>
        internal static string Message426UpgradeRequired {
            get {
                return ResourceManager.GetString("Message426UpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has sent too many requests in a given amount of time..
        /// </summary>
        internal static string Message429TooManyRequests {
            get {
                return ResourceManager.GetString("Message429TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item you requested is unavailable for legal reasons..
        /// </summary>
        internal static string Message451NotAvailableForLegalReasons {
            get {
                return ResourceManager.GetString("Message451NotAvailableForLegalReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal error or misconfiguration and was unable to complete your request..
        /// </summary>
        internal static string Message500InternalServerError {
            get {
                return ResourceManager.GetString("Message500InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality has not yet been implemented..
        /// </summary>
        internal static string Message501NotImplemented {
            get {
                return ResourceManager.GetString("Message501NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy server received an invalid response from an upstream server..
        /// </summary>
        internal static string Message502BadGateway {
            get {
                return ResourceManager.GetString("Message502BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is temporarily unable to process your request due to maintenance downtime or capacity problems. Please try again later..
        /// </summary>
        internal static string Message503ServiceUnavailable {
            get {
                return ResourceManager.GetString("Message503ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gateway did not receive a timely response from the upstream server or application..
        /// </summary>
        internal static string Message504GatewayTimeout {
            get {
                return ResourceManager.GetString("Message504GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variant for the requested URL is also a negotiable resource..
        /// </summary>
        internal static string Message506VariantAlsoNegotiates {
            get {
                return ResourceManager.GetString("Message506VariantAlsoNegotiates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource could not be stored because there is insufficient storage space left in your allocation..
        /// </summary>
        internal static string Message507InsufficientStorage {
            get {
                return ResourceManager.GetString("Message507InsufficientStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mandatory extension policy in the request is not accepted by the server for this resource..
        /// </summary>
        internal static string Message510NotExtended {
            get {
                return ResourceManager.GetString("Message510NotExtended", resourceCulture);
            }
        }
    }
}
